apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-dep
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      name: wp-dep
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: wp-cm
            - secretRef:
                name: wp-secret
          imagePullPolicy: Always
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: wp-pvc
