apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
spec:
  containers:
    - name: wordpress
      image: wordpress:latest
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: wp-cm
        - secretRef:
            name: wp-secret
      imagePullPolicy: Always 
  volumes:
    - name: wordpress-storage
      persistentVolumeClaim:
        claimName: wp-pvc
